import {
  AlertTriangle,
  ArrowDownRight,
  ArrowLeftRight,
  ArrowRight,
  ArrowUpRight,
  BadgeCheck,
  BookOpen,
  Briefcase,
  Building,
  CalendarClock,
  ChartBar,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  CircleDot,
  Clock,
  Coins,
  Copy,
  Download,
  Eye,
  FileSearch,
  FileText,
  Filter,
  Flag,
  Folder,
  GitMerge,
  Handshake,
  HelpCircle,
  History,
  IdCard,
  Inbox,
  Info,
  KanbanSquare,
  Key,
  Landmark,
  LayoutDashboard,
  LifeBuoy,
  Lock,
  type LucideIcon,
  Mail,
  MessageSquare,
  MoreHorizontal,
  Paperclip,
  Pause,
  Pencil,
  Play,
  Plus,
  PlusSquare,
  RefreshCcw,
  ScanSearch,
  Scroll,
  Search,
  Send,
  Settings,
  Shield,
  ShieldCheck,
  Sparkles,
  TrendingDown,
  TrendingUp,
  Upload,
  Users,
  Vote,
  X,
} from 'lucide-react'

const ICONS: Record<string, LucideIcon> = {
  'alert-triangle': AlertTriangle,
  'arrow-down-right': ArrowDownRight,
  'arrow-left-right': ArrowLeftRight,
  'arrow-right': ArrowRight,
  'arrow-up-right': ArrowUpRight,
  'badge-check': BadgeCheck,
  'book-open': BookOpen,
  briefcase: Briefcase,
  building: Building,
  'calendar-clock': CalendarClock,
  'chart-bar': ChartBar,
  check: Check,
  'check-circle': CheckCircle2,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  'circle-dot': CircleDot,
  clock: Clock,
  coins: Coins,
  copy: Copy,
  download: Download,
  eye: Eye,
  'file-search': FileSearch,
  'file-text': FileText,
  filter: Filter,
  flag: Flag,
  folder: Folder,
  'git-merge': GitMerge,
  handshake: Handshake,
  'help-circle': HelpCircle,
  history: History,
  'id-card': IdCard,
  inbox: Inbox,
  info: Info,
  'kanban-square': KanbanSquare,
  key: Key,
  landmark: Landmark,
  'layout-dashboard': LayoutDashboard,
  'life-buoy': LifeBuoy,
  lock: Lock,
  mail: Mail,
  'message-square': MessageSquare,
  more: MoreHorizontal,
  paperclip: Paperclip,
  pause: Pause,
  pencil: Pencil,
  play: Play,
  plus: Plus,
  'plus-square': PlusSquare,
  refresh: RefreshCcw,
  'scan-search': ScanSearch,
  scroll: Scroll,
  search: Search,
  send: Send,
  settings: Settings,
  shield: Shield,
  'shield-check': ShieldCheck,
  sparkles: Sparkles,
  'trending-down': TrendingDown,
  'trending-up': TrendingUp,
  upload: Upload,
  users: Users,
  vote: Vote,
  x: X,
}

export function Icon({
  name,
  size = 16,
  className,
}: {
  name: string
  size?: number
  className?: string
}) {
  const C = ICONS[name] ?? CircleDot
  return <C className={className} size={size} strokeWidth={1.75} />
}
