import {
  AlertTriangle,
  ArrowDown,
  ArrowDownRight,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUpRight,
  BadgeCheck,
  BookOpen,
  Briefcase,
  Building,
  CalendarClock,
  ChartBar,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  CircleDashed,
  CircleDot,
  Clock,
  Coins,
  Columns3,
  Copy,
  Download,
  ExternalLink,
  Eye,
  FilePlus,
  FileSearch,
  FileText,
  Filter,
  Flag,
  Folder,
  GitMerge,
  Handshake,
  HelpCircle,
  History,
  IdCard,
  Inbox,
  Info,
  KanbanSquare,
  Key,
  Landmark,
  LayoutDashboard,
  LifeBuoy,
  Lock,
  type LucideIcon,
  Mail,
  MessageSquare,
  MoreHorizontal,
  Paperclip,
  Pause,
  Pencil,
  Play,
  Plus,
  PlusSquare,
  RefreshCcw,
  RefreshCw,
  ScanSearch,
  Scroll,
  Search,
  Send,
  Settings,
  Shield,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  TrendingDown,
  TrendingUp,
  Upload,
  UserRound,
  Users,
  Vote,
  X,
  XCircle,
} from 'lucide-react'

const ICONS: Record<string, LucideIcon> = {
  'alert-triangle': AlertTriangle,
  'arrow-down': ArrowDown,
  'arrow-down-right': ArrowDownRight,
  'arrow-left': ArrowLeft,
  'arrow-left-right': ArrowLeftRight,
  'arrow-right': ArrowRight,
  'arrow-up-right': ArrowUpRight,
  'badge-check': BadgeCheck,
  'book-open': BookOpen,
  briefcase: Briefcase,
  building: Building,
  'calendar-clock': CalendarClock,
  'chart-bar': ChartBar,
  check: Check,
  'check-circle': CheckCircle2,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  'circle-dashed': CircleDashed,
  'circle-dot': CircleDot,
  clock: Clock,
  coins: Coins,
  'columns-3': Columns3,
  copy: Copy,
  download: Download,
  'external-link': ExternalLink,
  eye: Eye,
  'file-plus': FilePlus,
  'file-search': FileSearch,
  'file-text': FileText,
  filter: Filter,
  flag: Flag,
  folder: Folder,
  'git-merge': GitMerge,
  handshake: Handshake,
  'help-circle': HelpCircle,
  history: History,
  'id-card': IdCard,
  inbox: Inbox,
  info: Info,
  'kanban-square': KanbanSquare,
  key: Key,
  landmark: Landmark,
  'layout-dashboard': LayoutDashboard,
  'life-buoy': LifeBuoy,
  lock: Lock,
  mail: Mail,
  'message-square': MessageSquare,
  more: MoreHorizontal,
  paperclip: Paperclip,
  pause: Pause,
  pencil: Pencil,
  play: Play,
  plus: Plus,
  'plus-square': PlusSquare,
  refresh: RefreshCcw,
  'refresh-cw': RefreshCw,
  'scan-search': ScanSearch,
  scroll: Scroll,
  search: Search,
  send: Send,
  settings: Settings,
  shield: Shield,
  'shield-check': ShieldCheck,
  'sliders-horizontal': SlidersHorizontal,
  sparkles: Sparkles,
  'trending-down': TrendingDown,
  'trending-up': TrendingUp,
  upload: Upload,
  'user-round': UserRound,
  users: Users,
  vote: Vote,
  x: X,
  'x-circle': XCircle,
}

export function Icon({ name, size = 24, className }: { name: string; size?: number; className?: string }) {
  const C = ICONS[name] ?? CircleDot
  return <C className={className} size={size} strokeWidth={1.75} />
}
