import type { TransferRequest } from './types'

const MRDN = {
  cusip: '589543 10 2',
  issuer: 'Meridian Optics, Inc.',
  marketValuePerShare: 83.3,
  ticker: 'MRDN',
} as const

const HALC = {
  cusip: '402671 10 8',
  issuer: 'Halcyon Industrial Co.',
  marketValuePerShare: 47.6,
  ticker: 'HALC',
} as const

const RDG = {
  cusip: '765944 20 1',
  issuer: 'Ridgefield Energy Holdings',
  marketValuePerShare: 19.2,
  ticker: 'RDG',
} as const

const TGBX = {
  cusip: '871140 10 3',
  issuer: 'Teagan Biosciences',
  marketValuePerShare: 11.7,
  ticker: 'TGBX',
} as const

export const MOCK_TRANSFERS: TransferRequest[] = [
  // 1. Broker transfer with medallion issue + name variance — primary case
  {
    aiRecommendation: 'Approve with reviewer override on name variance (legitimate per KYC). Request medallion re-upload out-of-band.',
    assignedReviewer: { initials: 'DC', name: 'Daniel Chen' },
    auditEvents: [
      {
        actor: 'shareholder',
        actorName: 'Eleanor Hayes',
        at: '2026-04-16T15:02:00-04:00',
        detail: 'Uploaded stock power, photo ID, medallion guarantee, W-9 archive.',
        id: 'ev-1',
        kind: 'created',
        title: 'Shareholder submitted request',
        tone: 'ok',
      },
      {
        actor: 'proxi-ai',
        actorName: 'Proxi AI',
        at: '2026-04-16T15:03:04-04:00',
        detail: 'Textract finished 3 pages in 1.8s · hash 0x81fa…aa3e',
        id: 'ev-2',
        kind: 'ai-extracted',
        title: 'OCR pipeline run',
        tone: 'info',
      },
      {
        actor: 'proxi-ai',
        actorName: 'Proxi AI',
        at: '2026-04-16T15:03:19-04:00',
        detail: 'Stock power extraction complete · 14 fields · overall confidence 42%.',
        id: 'ev-3',
        kind: 'ai-extracted',
        title: 'Structured extraction',
        tone: 'info',
      },
      {
        actor: 'proxi-ai',
        actorName: 'Proxi AI',
        at: '2026-04-16T15:03:46-04:00',
        detail: 'Medallion stamp OCR scored 64%. Routed to reviewer queue.',
        id: 'ev-4',
        kind: 'ai-flagged',
        title: 'AI confidence under threshold',
        tone: 'warn',
      },
      {
        actor: 'system',
        actorName: 'Routing service',
        at: '2026-04-16T15:04:02-04:00',
        id: 'ev-5',
        kind: 'assigned',
        title: 'Assigned to Daniel Chen',
        tone: 'info',
      },
      {
        actor: 'proxi-ai',
        actorName: 'Proxi AI',
        at: '2026-04-16T15:06:11-04:00',
        detail: 'Ledger: "Eleanor M. Hayes". Form: "Elenor Hayes". Photo ID matches ledger (97%).',
        id: 'ev-6',
        kind: 'ai-suggested',
        title: 'Name variance — recommend reviewer override',
        tone: 'warn',
      },
    ],
    confidence: 42,
    confidenceBand: 'low',
    createdAt: '2026-04-16T15:02:00-04:00',
    destination: {
      accountNumber: '••••4512',
      accountTitle: 'Eleanor M. Hayes · IRA',
      brokerName: 'Fidelity Brokerage Services LLC',
      dtcParticipant: '0226',
      kind: 'broker',
      label: 'Fidelity · IRA ••4512',
    },
    documents: [
      {
        aiConfidence: 97,
        hash: '0x81fa…aa3e',
        id: 'd-1',
        name: 'Stock power.pdf',
        pages: 2,
        required: true,
        size: '482 KB',
        state: 'accepted',
        type: 'stock-power',
        uploadedAt: '2026-04-16T15:02:12-04:00',
      },
      {
        aiConfidence: 98,
        id: 'd-2',
        name: 'Photo ID · DL (CA).jpg',
        pages: 1,
        required: true,
        size: '1.1 MB',
        state: 'accepted',
        type: 'gov-id',
        uploadedAt: '2026-04-16T15:02:14-04:00',
      },
      {
        aiConfidence: 94,
        id: 'd-3',
        name: 'Liveness capture',
        pages: 1,
        required: true,
        size: '2.4 MB',
        state: 'accepted',
        type: 'liveness',
        uploadedAt: '2026-04-16T15:02:18-04:00',
      },
      {
        aiConfidence: 64,
        id: 'd-4',
        issueNote: 'Stamp partially cropped — reviewer requested re-upload.',
        name: 'Medallion guarantee.pdf',
        pages: 1,
        required: true,
        size: '220 KB',
        state: 'needs-reupload',
        type: 'medallion',
        uploadedAt: '2026-04-16T15:02:22-04:00',
      },
      {
        id: 'd-5',
        issueNote: 'On file from 2024 — address since changed. Refresh requested.',
        name: 'W-9 (2024 archive)',
        required: true,
        state: 'needs-reupload',
        type: 'w9',
      },
      {
        id: 'd-6',
        name: 'Destination account statement',
        required: true,
        state: 'accepted',
        size: '118 KB',
        type: 'account-statement',
        uploadedAt: '2026-04-16T15:02:25-04:00',
      },
    ],
    exceptions: [
      {
        blocking: false,
        code: 'NAME_VARIANCE',
        description: 'Stock power shows "Elenor Hayes". Ledger has "Eleanor M. Hayes". Photo ID and W-9 match ledger.',
        id: 'x-1',
        openedAt: '2026-04-16T15:03:19-04:00',
        severity: 'medium',
        suggestedAction: 'Reviewer override with note — consistent with historical practice.',
        title: 'Name variance vs. ledger',
      },
      {
        blocking: true,
        code: 'MEDALLION_CROPPED',
        description: 'Medallion stamp OCR scored 64%. Stamp edge is cropped in scan.',
        id: 'x-2',
        openedAt: '2026-04-16T15:03:46-04:00',
        severity: 'high',
        suggestedAction: 'Request re-upload of medallion guarantee at higher resolution.',
        title: 'Medallion stamp not fully verifiable',
      },
      {
        blocking: true,
        code: 'W9_STALE',
        description: 'W-9 on file predates the last address change (2025-11-02).',
        id: 'x-3',
        openedAt: '2026-04-16T15:03:51-04:00',
        severity: 'medium',
        suggestedAction: 'Send pre-filled W-9 refresh link to holder.',
        title: 'Stale tax form',
      },
    ],
    extractedFields: [
      {
        confidence: 42,
        key: 'holder',
        label: 'Registered holder',
        ledgerValue: 'Eleanor M. Hayes',
        note: 'Photo ID (97% match) confirms "Eleanor M. Hayes". Historical practice permits reviewer override on spelling variance.',
        section: 'parties',
        sourceDoc: 'Stock power.pdf',
        sourcePage: 1,
        sourceSnippet: 'Signer block: "Elenor Hayes"',
        value: 'Elenor Hayes',
        warning: 'Name variance vs. ledger of record',
      },
      {
        confidence: 96,
        key: 'holder-account',
        label: 'Account of record',
        section: 'parties',
        sourceDoc: 'Ledger lookup',
        sourcePage: 1,
        sourceSnippet: 'MRDN-DRS-0019428 · Individual · CA',
        value: 'MRDN-DRS-0019428',
      },
      {
        confidence: 98,
        key: 'issuer',
        label: 'Issuer & CUSIP',
        section: 'transfer',
        sourceDoc: 'Stock power.pdf',
        sourcePage: 1,
        sourceSnippet: 'Meridian Optics, Inc. · CUSIP 589543 10 2',
        value: 'Meridian Optics, Inc. · 589543 10 2',
      },
      {
        confidence: 97,
        key: 'shares',
        label: 'Shares to transfer',
        section: 'transfer',
        sourceDoc: 'Stock power.pdf',
        sourcePage: 1,
        sourceSnippet: '"Five Hundred (500)" — numeric + written cross-check.',
        value: '500',
      },
      {
        confidence: 91,
        key: 'holding-type',
        label: 'Holding type',
        section: 'transfer',
        sourceDoc: 'Ledger lookup',
        sourcePage: 1,
        value: 'DRS book-entry',
      },
      {
        confidence: 94,
        key: 'broker',
        label: 'Destination broker (DTC participant)',
        section: 'destination',
        sourceDoc: 'Stock power.pdf',
        sourcePage: 2,
        sourceSnippet: 'DTC participant 0226 · National Financial (Fidelity)',
        value: 'Fidelity · DTC 0226',
      },
      {
        confidence: 92,
        key: 'account',
        label: 'Destination account',
        section: 'destination',
        sourceDoc: 'Stock power.pdf',
        sourcePage: 2,
        sourceSnippet: 'IRA registration · account ending 4512',
        value: '••••••4512 · IRA',
      },
      {
        confidence: 64,
        key: 'medallion',
        label: 'Medallion signature guarantee',
        note: 'Signature scored 72% · stamp OCR 64%. Falls below the 85% auto-approval threshold.',
        section: 'authorizations',
        sourceDoc: 'Medallion guarantee.pdf',
        sourcePage: 1,
        sourceSnippet: 'STA surety · ID MGA-2189',
        value: 'STA surety · MGA-2189',
        warning: 'Stamp image is partially cropped',
      },
      {
        confidence: 88,
        key: 'w9',
        label: 'Tax form (W-9)',
        note: 'Exists but predates the 2025-11-02 address change. Refresh recommended before posting.',
        section: 'compliance',
        sourceDoc: 'W-9 (2024 archive)',
        sourcePage: 1,
        value: 'On file · refresh recommended',
      },
    ],
    holder: {
      accountNumber: 'MRDN-DRS-0019428',
      id: 'h-1',
      initials: 'EH',
      kycExpiresAt: '2027-03-12',
      mailingCity: 'San Mateo',
      mailingState: 'CA',
      name: 'Eleanor M. Hayes',
      registration: 'Individual',
      taxProfile: 'W-9',
    },
    holding: {
      availableShares: 1240,
      cusip: MRDN.cusip,
      issuer: MRDN.issuer,
      marketValuePerShare: MRDN.marketValuePerShare,
      ticker: MRDN.ticker,
      type: 'DRS',
    },
    id: 'TR-120458',
    issuerName: MRDN.issuer,
    kyc: {
      addressMatch: 96,
      idMatch: 97,
      lastRunAt: '2026-04-16T15:02:30-04:00',
      liveness: 'passed',
      ofac: 'cleared',
      status: 'attention',
    },
    medallion: {
      amount: 'Up to $100,000',
      guarantor: 'STA surety · MGA-2189',
      note: 'Stamp edge cropped — reviewer requested re-upload.',
      status: 'cropped',
    },
    missingBlockers: [
      {
        action: { href: '#upload-medallion', label: 'Re-upload medallion' },
        howToFix: 'Scan the medallion page flat with the full STA / MSP stamp inside the page boundary. PDF or JPG · 300 dpi minimum.',
        label: 'Medallion signature guarantee needs a clean re-scan',
        severity: 'high',
      },
      {
        action: { href: '#upload-w9', label: 'Refresh W-9' },
        howToFix: 'Confirm your mailing address, then sign and date Part II of Form W-9. Proxi will pre-fill known fields.',
        label: 'W-9 on file predates your current address',
        severity: 'medium',
      },
    ],
    missingItems: ['Re-upload medallion guarantee', 'Refresh W-9 to current address'],
    nextStepForReviewer: 'Decide on name-variance override; request medallion re-upload; pause SLA on W-9 refresh.',
    nextStepForShareholder:
      'Re-upload medallion with full stamp visible and refresh your W-9 to the current address. Your SLA clock is paused until both arrive.',
    partial: true,
    reviewerNotes: [
      {
        at: '2026-04-16T15:48:00-04:00',
        author: 'Daniel Chen',
        authorRole: 'Reviewer · Senior',
        body: 'Name variance confirmed against photo ID (match 97%). Awaiting re-uploaded medallion stamp before final approval.',
        id: 'n-1',
        tag: 'override-draft',
      },
    ],
    shareCount: 500,
    shareValue: 41_650,
    sla: {
      agingState: 'at-risk',
      dueAt: '2026-04-16T20:00:00-04:00',
      expectedTurnaroundHours: 6,
      pausedReason: 'Pending holder re-upload',
      submittedAt: '2026-04-16T15:02:00-04:00',
    },
    stage: 'reviewer',
    status: 'needs-info',
    transferType: 'drs-to-broker',
  },
  // 2. Clean trust re-registration — approved, awaiting post
  {
    assignedReviewer: { initials: 'RP', name: 'Rhea Patel' },
    auditEvents: [
      {
        actor: 'shareholder',
        actorName: 'Theodore Nguyen',
        at: '2026-04-15T09:14:00-04:00',
        id: 'ev-1',
        kind: 'created',
        title: 'Request submitted via guided intake',
        tone: 'ok',
      },
      {
        actor: 'proxi-ai',
        actorName: 'Proxi AI',
        at: '2026-04-15T09:14:31-04:00',
        detail: 'Overall confidence 94% · all fields above threshold.',
        id: 'ev-2',
        kind: 'ai-extracted',
        title: 'Straight-through candidate',
        tone: 'ok',
      },
      {
        actor: 'reviewer',
        actorName: 'Rhea Patel',
        at: '2026-04-15T11:22:00-04:00',
        id: 'ev-3',
        kind: 'approved',
        title: 'Approved',
        tone: 'ok',
      },
    ],
    confidence: 94,
    confidenceBand: 'high',
    createdAt: '2026-04-15T09:14:00-04:00',
    destination: {
      kind: 'trust',
      label: 'Nguyen Family Trust · 2019',
      registrationType: 'Revocable living trust',
      trusteeNames: ['Theodore Nguyen', 'Mei-Ling Nguyen'],
    },
    documents: [
      {
        aiConfidence: 96,
        id: 'd-1',
        name: 'Stock power.pdf',
        required: true,
        size: '512 KB',
        state: 'accepted',
        type: 'stock-power',
      },
      {
        aiConfidence: 97,
        id: 'd-2',
        name: 'Certificate of trust.pdf',
        required: true,
        size: '810 KB',
        state: 'accepted',
        type: 'trust-certificate',
      },
      {
        aiConfidence: 99,
        id: 'd-3',
        name: 'Photo ID · Passport',
        required: true,
        state: 'accepted',
        type: 'gov-id',
      },
    ],
    exceptions: [],
    extractedFields: [
      {
        confidence: 98,
        key: 'issuer',
        label: 'Issuer',
        sourceDoc: 'Stock power.pdf',
        sourcePage: 1,
        value: 'Halcyon Industrial Co.',
      },
      {
        confidence: 97,
        key: 'shares',
        label: 'Shares',
        sourceDoc: 'Stock power.pdf',
        sourcePage: 1,
        value: '200',
      },
      {
        confidence: 91,
        key: 'new-reg',
        label: 'New registration',
        sourceDoc: 'Certificate of trust.pdf',
        sourcePage: 1,
        value: 'Nguyen Family Trust · 2019',
      },
    ],
    holder: {
      accountNumber: 'HALC-DRS-0004121',
      id: 'h-2',
      initials: 'TN',
      name: 'Theodore Nguyen',
      registration: 'Individual',
      taxProfile: 'W-9',
    },
    holding: {
      availableShares: 800,
      cusip: HALC.cusip,
      issuer: HALC.issuer,
      marketValuePerShare: HALC.marketValuePerShare,
      ticker: HALC.ticker,
      type: 'DRS',
    },
    id: 'TR-120460',
    issuerName: HALC.issuer,
    kyc: {
      addressMatch: 98,
      idMatch: 99,
      lastRunAt: '2026-04-15T09:15:10-04:00',
      liveness: 'passed',
      ofac: 'cleared',
      status: 'passed',
    },
    medallion: {
      belowThreshold: true,
      note: 'Below $25,000 intra-family threshold.',
      status: 'waived-under-threshold',
      thresholdUsd: 25_000,
    },
    missingItems: [],
    nextStepForShareholder: 'Posting to ledger — confirmation will follow within 2 hours.',
    partial: false,
    reviewerNotes: [],
    shareCount: 200,
    shareValue: 9_520,
    sla: {
      agingState: 'on-track',
      dueAt: '2026-04-15T15:14:00-04:00',
      expectedTurnaroundHours: 6,
      submittedAt: '2026-04-15T09:14:00-04:00',
    },
    stage: 'posting',
    status: 'approved',
    transferType: 'drs-to-drs',
  },
  // 3. Posted ESPP DRS to DRS — historical reference
  {
    auditEvents: [
      {
        actor: 'proxi-ai',
        actorName: 'Proxi AI',
        at: '2026-03-28T10:02:00-04:00',
        id: 'ev-1',
        kind: 'posted',
        title: 'Posted to ledger · journal 0x91c2…',
        tone: 'ok',
      },
    ],
    confidence: 97,
    confidenceBand: 'high',
    createdAt: '2026-03-27T16:40:00-04:00',
    destination: {
      kind: 'individual',
      label: 'Sujata R. Iyer · DRS (new registration)',
      registrationType: 'Individual',
    },
    documents: [],
    exceptions: [],
    extractedFields: [],
    holder: {
      accountNumber: 'TGBX-ESPP-0019121',
      id: 'h-3',
      initials: 'SI',
      name: 'Sujata Iyer',
      registration: 'ESPP · vested',
      taxProfile: 'W-9',
    },
    holding: {
      availableShares: 180,
      cusip: TGBX.cusip,
      issuer: TGBX.issuer,
      marketValuePerShare: TGBX.marketValuePerShare,
      ticker: TGBX.ticker,
      type: 'ESPP',
    },
    id: 'TR-120467',
    issuerName: TGBX.issuer,
    kyc: {
      addressMatch: 99,
      idMatch: 99,
      liveness: 'passed',
      ofac: 'cleared',
      status: 'passed',
    },
    medallion: { belowThreshold: true, status: 'waived-under-threshold', thresholdUsd: 25_000 },
    missingItems: [],
    partial: false,
    reviewerNotes: [],
    shareCount: 180,
    shareValue: 2_106,
    sla: {
      agingState: 'on-track',
      dueAt: '2026-03-28T10:40:00-04:00',
      expectedTurnaroundHours: 12,
      submittedAt: '2026-03-27T16:40:00-04:00',
    },
    stage: 'complete',
    status: 'posted',
    transferType: 'drs-to-drs',
  },
  // 4. Entity · DRS → certificate issuance · medium confidence
  {
    assignedReviewer: { initials: 'MR', name: 'Mateo Rivas' },
    auditEvents: [
      {
        actor: 'shareholder',
        actorName: 'Okoye Holdings LLC',
        at: '2026-04-16T11:05:00-04:00',
        id: 'ev-1',
        kind: 'created',
        title: 'Request submitted',
        tone: 'ok',
      },
      {
        actor: 'proxi-ai',
        actorName: 'Proxi AI',
        at: '2026-04-16T11:06:20-04:00',
        detail: 'Entity officer signature verification 78%.',
        id: 'ev-2',
        kind: 'ai-flagged',
        title: 'Officer signature low confidence',
        tone: 'warn',
      },
    ],
    confidence: 78,
    confidenceBand: 'medium',
    createdAt: '2026-04-16T11:05:00-04:00',
    destination: {
      kind: 'certificate',
      label: 'Physical certificate · Okoye Holdings LLC',
      mailingAddress: '1401 Beacon St, Boston, MA 02446',
    },
    documents: [
      {
        aiConfidence: 82,
        id: 'd-1',
        name: 'Board resolution.pdf',
        required: true,
        state: 'accepted',
        type: 'stock-power',
      },
      {
        aiConfidence: 78,
        id: 'd-2',
        name: 'Officer signature card.pdf',
        required: true,
        state: 'accepted',
        type: 'notary',
      },
      {
        id: 'd-3',
        issueNote: 'Below waiver threshold — affidavit of loss accepted.',
        name: 'Medallion (waived)',
        required: false,
        state: 'accepted',
        type: 'medallion',
      },
    ],
    exceptions: [
      {
        blocking: false,
        code: 'OFFICER_SIG_LOW',
        description: 'OCR on officer signature at 78% vs. 85% threshold.',
        id: 'x-1',
        openedAt: '2026-04-16T11:06:20-04:00',
        severity: 'low',
        suggestedAction: 'Cross-check with most recent signature card on file.',
        title: 'Officer signature confidence below threshold',
      },
    ],
    extractedFields: [
      {
        confidence: 98,
        key: 'entity',
        label: 'Entity',
        sourceDoc: 'Board resolution.pdf',
        sourcePage: 1,
        value: 'Okoye Holdings LLC',
      },
      {
        confidence: 97,
        key: 'shares',
        label: 'Shares to certificate',
        sourceDoc: 'Board resolution.pdf',
        sourcePage: 1,
        value: '1,000',
      },
      {
        confidence: 78,
        key: 'officer',
        label: 'Officer signature',
        note: 'OCR below threshold — verify against signature card on file.',
        sourceDoc: 'Officer signature card.pdf',
        sourcePage: 1,
        value: 'Adaeze Okoye, Manager',
        warning: 'Signature confidence below threshold',
      },
    ],
    holder: {
      accountNumber: 'RDG-DRS-0008044',
      id: 'h-4',
      initials: 'OH',
      name: 'Okoye Holdings LLC',
      registration: 'Entity · LLC',
      taxProfile: 'W-9',
    },
    holding: {
      availableShares: 4500,
      cusip: RDG.cusip,
      issuer: RDG.issuer,
      marketValuePerShare: RDG.marketValuePerShare,
      ticker: RDG.ticker,
      type: 'DRS',
    },
    id: 'TR-120471',
    issuerName: RDG.issuer,
    kyc: {
      addressMatch: 92,
      idMatch: 94,
      lastRunAt: '2026-04-16T11:06:00-04:00',
      liveness: null,
      ofac: 'cleared',
      status: 'passed',
    },
    medallion: {
      belowThreshold: false,
      note: 'Affidavit of loss used in lieu of medallion (entity action).',
      status: 'waived-affidavit',
    },
    missingItems: [],
    nextStepForReviewer: 'Cross-check officer signature against current signature card on file.',
    partial: true,
    reviewerNotes: [],
    shareCount: 1000,
    shareValue: 19_200,
    sla: {
      agingState: 'on-track',
      dueAt: '2026-04-17T11:05:00-04:00',
      expectedTurnaroundHours: 24,
      submittedAt: '2026-04-16T11:05:00-04:00',
    },
    stage: 'reviewer',
    status: 'in-review',
    transferType: 'drs-to-cert',
  },
  // 5. Paper certificate deposit with fraud escalation
  {
    assignedReviewer: { initials: 'AK', name: 'Aisha Khan' },
    auditEvents: [
      {
        actor: 'shareholder',
        actorName: 'Priya Shah',
        at: '2026-04-14T10:17:00-04:00',
        id: 'ev-1',
        kind: 'created',
        title: 'Paper cert deposit initiated',
        tone: 'ok',
      },
      {
        actor: 'proxi-ai',
        actorName: 'Proxi AI',
        at: '2026-04-14T10:18:44-04:00',
        detail: 'Certificate number MRDN-CT-098211 not found in issuer registry.',
        id: 'ev-2',
        kind: 'ai-flagged',
        title: 'Certificate number not recognised',
        tone: 'danger',
      },
      {
        actor: 'reviewer',
        actorName: 'Aisha Khan',
        at: '2026-04-14T10:45:00-04:00',
        id: 'ev-3',
        kind: 'escalated',
        title: 'Escalated to compliance',
        tone: 'warn',
      },
    ],
    confidence: 31,
    confidenceBand: 'low',
    createdAt: '2026-04-14T10:17:00-04:00',
    destination: {
      kind: 'individual',
      label: 'Priya Shah · DRS',
      registrationType: 'Individual',
    },
    documents: [
      {
        aiConfidence: 38,
        id: 'd-1',
        issueNote: 'Certificate number does not match issuer registry.',
        name: 'Paper certificate scan.pdf',
        required: true,
        state: 'rejected',
        type: 'stock-power',
      },
    ],
    exceptions: [
      {
        blocking: true,
        code: 'CERT_NOT_IN_REGISTRY',
        description: 'Certificate number MRDN-CT-098211 was never issued by Meridian Optics per issuer registry.',
        id: 'x-1',
        openedAt: '2026-04-14T10:18:44-04:00',
        severity: 'high',
        suggestedAction: 'Escalate to compliance · request original document.',
        title: 'Possible fraudulent certificate',
      },
    ],
    extractedFields: [
      {
        confidence: 31,
        key: 'cert-number',
        label: 'Certificate number',
        sourceDoc: 'Paper certificate scan.pdf',
        sourcePage: 1,
        value: 'MRDN-CT-098211',
        warning: 'Not found in issuer registry',
      },
    ],
    holder: {
      accountNumber: 'MRDN-NEW-0032015',
      id: 'h-5',
      initials: 'PS',
      name: 'Priya Shah',
      registration: 'Individual · new',
      taxProfile: 'W-9',
    },
    holding: {
      availableShares: 0,
      cusip: MRDN.cusip,
      issuer: MRDN.issuer,
      marketValuePerShare: MRDN.marketValuePerShare,
      ticker: MRDN.ticker,
      type: 'Cert (paper)',
    },
    id: 'TR-120482',
    issuerName: MRDN.issuer,
    kyc: {
      addressMatch: 94,
      idMatch: 96,
      liveness: 'passed',
      ofac: 'cleared',
      status: 'passed',
    },
    medallion: { status: 'missing' },
    missingItems: ['Original paper certificate for forensic inspection'],
    nextStepForReviewer: 'Hold pending compliance review. Do not post.',
    partial: false,
    reviewerNotes: [
      {
        at: '2026-04-14T10:46:12-04:00',
        author: 'Aisha Khan',
        authorRole: 'Reviewer · Compliance',
        body: 'Certificate number not in issuer registry. Escalated to compliance for forensic inspection.',
        id: 'n-1',
        tag: 'fraud-review',
      },
    ],
    shareCount: 150,
    shareValue: 12_495,
    sla: {
      agingState: 'overdue',
      dueAt: '2026-04-15T10:17:00-04:00',
      expectedTurnaroundHours: 24,
      pausedReason: 'Compliance hold',
      submittedAt: '2026-04-14T10:17:00-04:00',
    },
    stage: 'reviewer',
    status: 'escalated',
    transferType: 'cert-to-drs',
  },
  // 6. Gift DRS-to-DRS — draft from guided intake
  {
    auditEvents: [
      {
        actor: 'shareholder',
        actorName: 'Eleanor Hayes',
        at: '2026-04-16T12:21:00-04:00',
        id: 'ev-1',
        kind: 'created',
        title: 'Guided intake started',
        tone: 'info',
      },
    ],
    confidence: 0,
    confidenceBand: 'low',
    createdAt: '2026-04-16T12:21:00-04:00',
    destination: {
      kind: 'individual',
      label: 'Yvonne Park · DRS (new registration)',
      registrationType: 'Individual',
    },
    documents: [
      {
        id: 'd-1',
        name: 'Stock power / gift instruction',
        required: true,
        state: 'missing',
        type: 'stock-power',
      },
      { id: 'd-2', name: 'Government-issued ID', required: true, state: 'missing', type: 'gov-id' },
    ],
    exceptions: [],
    extractedFields: [],
    holder: {
      accountNumber: 'MRDN-DRS-0019428',
      id: 'h-1',
      initials: 'EH',
      name: 'Eleanor M. Hayes',
      registration: 'Individual',
      taxProfile: 'W-9',
    },
    holding: {
      availableShares: 1240,
      cusip: MRDN.cusip,
      issuer: MRDN.issuer,
      marketValuePerShare: MRDN.marketValuePerShare,
      ticker: MRDN.ticker,
      type: 'DRS',
    },
    id: 'TR-120491',
    issuerName: MRDN.issuer,
    kyc: {
      addressMatch: null,
      idMatch: null,
      liveness: null,
      ofac: null,
      status: 'pending',
    },
    medallion: { belowThreshold: true, status: 'unknown-guarantor', thresholdUsd: 25_000 },
    missingBlockers: [
      {
        action: { href: '/investor/transfer/new', label: 'Continue intake' },
        howToFix: 'Proxi generates the stock power from your inputs — finish the destination and document steps.',
        label: 'Signed stock power has not been generated yet',
        severity: 'high',
      },
      {
        action: { href: '/investor/transfer/new', label: 'Continue intake' },
        howToFix: 'Upload a valid government-issued photo ID and complete a 10-second liveness capture.',
        label: 'Identity verification not yet completed',
        severity: 'high',
      },
    ],
    missingItems: ['Upload stock power', 'Upload photo ID', 'Complete liveness capture'],
    nextStepForShareholder: 'Finish guided intake to submit this transfer. Proxi has saved your progress.',
    partial: true,
    reviewerNotes: [],
    shareCount: 800,
    shareValue: 66_640,
    sla: {
      agingState: 'on-track',
      dueAt: '2026-04-17T12:21:00-04:00',
      expectedTurnaroundHours: 24,
      submittedAt: '2026-04-16T12:21:00-04:00',
    },
    stage: 'intake',
    status: 'draft',
    transferType: 'internal-family',
  },
]

export function listTransfers(): TransferRequest[] {
  return MOCK_TRANSFERS
}

export function listTransfersForHolder(holderId: string): TransferRequest[] {
  return MOCK_TRANSFERS.filter(t => t.holder.id === holderId)
}

export function getTransfer(id: string): TransferRequest {
  return MOCK_TRANSFERS.find(t => t.id.toLowerCase() === id.toLowerCase()) ?? MOCK_TRANSFERS[0]
}
