/**
 * Pure dividend statement renderer.
 *
 * Two flavours are exported:
 *
 *   - `buildStatementView()` — flattens the persisted statement row plus
 *     the related declaration/issuer/security/entitlement/payment context
 *     into a single readable projection. The statement endpoint returns
 *     this directly; the shareholder-portal HTML view consumes it; the
 *     PDF renderer (when added) takes the same shape as input.
 *
 *   - `renderStatementHtml()` — server-rendered HTML statement, suitable
 *     for shareholder downloads and as the input to a future PDF
 *     pipeline (puppeteer, wkhtmltopdf). The renderer is intentionally
 *     standalone: no React, no template engine, and no third-party
 *     dependency, so it can be invoked from any context (queue worker,
 *     cron, or HTTP handler) without lifecycle concerns.
 *
 * The HTML output is print-ready: it uses inline styles, a fixed page
 * width, and a compliance disclaimer. PDF generation is intentionally
 * not implemented inline. The intended abstraction is:
 *
 *   const html = renderStatementHtml(view)
 *   const pdf  = await pdfGenerator.fromHtml(html)   // platform-specific
 *
 * Adding a `DividendPdfGenerator` injectable later wires through this
 * boundary without changing any of the consumers.
 */

import { centsToDecimalString } from './dividends.csv.js'
import type {
  DividendEntitlement,
  DividendEvent,
  DividendIssuerSummary,
  DividendPayment,
  DividendSecuritySummary,
  DividendStatement,
} from './dividends.types.js'

// ----------------------------------------------------------------------
// View projection
// ----------------------------------------------------------------------

export interface StatementShareholderInfo {
  id: string
  /** Best-effort display name (legal name or registered holder display). */
  legalName?: string
  email?: string
  /** Free-form formatted address (single string). */
  mailingAddress?: string
  /** Tax residency country code (ISO 2-letter), if known. */
  taxResidency?: string
}

/**
 * Flat, render-ready projection of a dividend statement. Currency formatting
 * is left to the consumer — amounts are exposed both as integer cents
 * (canonical) and as decimal strings (`"123.45"`) for direct embedding.
 */
export interface DividendStatementView {
  statementId: string
  statementDate: string
  statementStatus: DividendStatement['status']

  /** Stable platform-generated statement number. */
  statementNumber: string

  issuer: DividendIssuerSummary
  security: DividendSecuritySummary
  shareholder: StatementShareholderInfo

  declaration: {
    id: string
    kind: DividendEvent['kind']
    rateType: DividendEvent['rateType']
    rateAmount: string
    declarationDate: string
    recordDate: string
    exDividendDate?: string
    paymentDate: string
  }

  amounts: {
    sharesEligible: string
    grossAmountCents: number
    grossAmountDecimal: string
    withholdingPct: string
    withholdingCents: number
    withholdingDecimal: string
    netAmountCents: number
    netAmountDecimal: string
    currency: string
  }

  payment?: {
    method: DividendPayment['method']
    status: DividendPayment['status']
    externalRef?: string
    paidAt?: string
  }

  /** Generated server-side at render time. */
  generatedAt: string

  /** Static disclaimer text — included in JSON responses for transparency. */
  disclaimer: string
}

const DEFAULT_DISCLAIMER =
  'This is a platform-generated dividend payment statement. ' +
  'It is provided for informational purposes only and is not tax advice. ' +
  'Consult your tax advisor regarding the tax treatment of dividend payments.'

export interface BuildStatementViewInput {
  statement: DividendStatement
  declaration: DividendEvent
  entitlement: DividendEntitlement
  issuer: DividendIssuerSummary
  security: DividendSecuritySummary
  shareholder: StatementShareholderInfo
  payment?: DividendPayment
  /** Override the autogenerated statement number (defaults to `STMT-${id}`). */
  statementNumber?: string
  /** Override the disclaimer text. */
  disclaimer?: string
  /** Test seam — defaults to `new Date()`. */
  generatedAt?: Date
}

export function buildStatementView(input: BuildStatementViewInput): DividendStatementView {
  const { declaration, entitlement, issuer, security, shareholder, statement, payment } = input
  const generatedAt = (input.generatedAt ?? new Date()).toISOString()
  return {
    amounts: {
      currency: statement.currency,
      grossAmountCents: statement.grossAmountCents,
      grossAmountDecimal: centsToDecimalString(statement.grossAmountCents),
      netAmountCents: statement.netAmountCents,
      netAmountDecimal: centsToDecimalString(statement.netAmountCents),
      sharesEligible: entitlement.sharesHeld,
      withholdingCents: statement.withholdingCents,
      withholdingDecimal: centsToDecimalString(statement.withholdingCents),
      withholdingPct: entitlement.withholdingPct,
    },
    declaration: {
      declarationDate: declaration.declarationDate,
      exDividendDate: declaration.exDividendDate,
      id: declaration.id,
      kind: declaration.kind,
      paymentDate: declaration.paymentDate,
      rateAmount: declaration.rateAmount,
      rateType: declaration.rateType,
      recordDate: declaration.recordDate,
    },
    disclaimer: input.disclaimer ?? DEFAULT_DISCLAIMER,
    generatedAt,
    issuer,
    payment: payment
      ? {
          externalRef: payment.externalRef,
          method: payment.method,
          paidAt: payment.paidAt ? payment.paidAt.toISOString() : undefined,
          status: payment.status,
        }
      : undefined,
    security,
    shareholder,
    statementDate: statement.statementDate,
    statementId: statement.id,
    statementNumber: input.statementNumber ?? `STMT-${statement.id.replace(/^dst_/, '').toUpperCase()}`,
    statementStatus: statement.status,
  }
}

// ----------------------------------------------------------------------
// HTML rendering
// ----------------------------------------------------------------------

/** Minimal HTML escape for safe interpolation into the statement template. */
function htmlEscape(value: string | number | undefined | null): string {
  if (value === null || value === undefined) return ''
  return String(value).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#39;')
}

function formatCurrency(decimal: string, currency: string): string {
  return `${currency} ${decimal}`
}

function dl(label: string, value: string | undefined): string {
  if (!value) return ''
  return `<div class="row"><dt>${htmlEscape(label)}</dt><dd>${htmlEscape(value)}</dd></div>`
}

/**
 * Render a print-ready HTML statement. The output is a complete document
 * (`<!doctype html>`...`</html>`) so it can be saved as `.html` and
 * opened directly, or piped into a PDF generator (puppeteer/wkhtmltopdf).
 *
 * Style choices:
 *   - Inline `<style>` block (no external CSS) for portability.
 *   - 8.5"-letter page width with safe print margins.
 *   - High-contrast typography; numbers in tabular-nums for alignment.
 */
export function renderStatementHtml(view: DividendStatementView): string {
  const a = view.amounts
  const decl = view.declaration
  const issuerName = view.issuer.legalName ?? view.issuer.id
  const securityLabel = [view.security.name, view.security.symbol].filter(Boolean).join(' · ')
  const accountLine = view.shareholder.legalName ?? view.shareholder.id

  const paymentBlock = view.payment
    ? `
        <h2>Payment</h2>
        <dl>
          ${dl('Method', view.payment.method)}
          ${dl('Status', view.payment.status)}
          ${dl('Reference', view.payment.externalRef)}
          ${dl('Paid at', view.payment.paidAt)}
        </dl>`
    : ''

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>Dividend Statement ${htmlEscape(view.statementNumber)}</title>
<style>
  :root {
    --fg: #0f172a;
    --muted: #475569;
    --line: #e2e8f0;
    --accent: #1e3a8a;
  }
  * { box-sizing: border-box; }
  html, body {
    margin: 0;
    padding: 0;
    color: var(--fg);
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
    font-size: 13px;
    line-height: 1.45;
    background: #fff;
  }
  .page {
    max-width: 720px;
    margin: 32px auto;
    padding: 32px 40px;
    background: #fff;
  }
  header {
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
    border-bottom: 1px solid var(--line);
    padding-bottom: 16px;
    margin-bottom: 20px;
  }
  header .meta { text-align: right; color: var(--muted); }
  header h1 {
    margin: 0 0 4px;
    font-size: 18px;
    color: var(--accent);
    letter-spacing: 0.2px;
  }
  h2 {
    font-size: 13px;
    text-transform: uppercase;
    letter-spacing: 0.6px;
    color: var(--muted);
    margin: 22px 0 8px;
  }
  dl { margin: 0; padding: 0; }
  .row {
    display: flex;
    justify-content: space-between;
    border-bottom: 1px dashed var(--line);
    padding: 6px 0;
  }
  dt, dd { margin: 0; }
  dt { color: var(--muted); }
  dd { font-variant-numeric: tabular-nums; }
  .totals {
    margin-top: 12px;
    padding: 14px 16px;
    border: 1px solid var(--line);
    border-radius: 6px;
    background: #f8fafc;
  }
  .totals .row { border: 0; padding: 4px 0; }
  .totals .net {
    border-top: 2px solid var(--fg);
    padding-top: 10px;
    margin-top: 6px;
    font-weight: 600;
    font-size: 15px;
  }
  .disclaimer {
    margin-top: 28px;
    padding-top: 14px;
    border-top: 1px solid var(--line);
    color: var(--muted);
    font-size: 11px;
    line-height: 1.5;
  }
  @media print {
    .page { margin: 0; padding: 24px; }
  }
</style>
</head>
<body>
  <div class="page">
    <header>
      <div>
        <h1>${htmlEscape(issuerName)}</h1>
        <div>${htmlEscape(securityLabel)}</div>
      </div>
      <div class="meta">
        <div><strong>Dividend Statement</strong></div>
        <div>${htmlEscape(view.statementNumber)}</div>
        <div>Statement date: ${htmlEscape(view.statementDate)}</div>
      </div>
    </header>

    <h2>Shareholder</h2>
    <dl>
      ${dl('Account', accountLine)}
      ${dl('Shareholder ID', view.shareholder.id)}
      ${dl('Tax residency', view.shareholder.taxResidency)}
      ${dl('Mailing address', view.shareholder.mailingAddress)}
    </dl>

    <h2>Dividend</h2>
    <dl>
      ${dl('Type', decl.kind)}
      ${dl('Rate', `${decl.rateAmount} (${decl.rateType})`)}
      ${dl('Declaration date', decl.declarationDate)}
      ${dl('Ex-dividend date', decl.exDividendDate)}
      ${dl('Record date', decl.recordDate)}
      ${dl('Payment date', decl.paymentDate)}
    </dl>

    <h2>Amounts</h2>
    <div class="totals">
      <div class="row"><dt>Shares eligible</dt><dd>${htmlEscape(a.sharesEligible)}</dd></div>
      <div class="row"><dt>Gross amount</dt><dd>${htmlEscape(formatCurrency(a.grossAmountDecimal, a.currency))}</dd></div>
      <div class="row"><dt>Withholding (${htmlEscape(a.withholdingPct)}%)</dt><dd>(${htmlEscape(formatCurrency(a.withholdingDecimal, a.currency))})</dd></div>
      <div class="row net"><dt>Net amount</dt><dd>${htmlEscape(formatCurrency(a.netAmountDecimal, a.currency))}</dd></div>
    </div>

    ${paymentBlock}

    <p class="disclaimer">${htmlEscape(view.disclaimer)}</p>
    <p class="disclaimer">Generated ${htmlEscape(view.generatedAt)} · Statement ID ${htmlEscape(view.statementId)}</p>
  </div>
</body>
</html>`
}

/**
 * Boundary type for a future PDF generator. Wiring this up is out of
 * scope here — the dividend module produces HTML and emits a structured
 * `DividendStatementView` so any downstream renderer can plug in
 * without further changes inside the dividend module.
 */
export interface DividendPdfGenerator {
  fromHtml(html: string, options?: { filename?: string }): Promise<Uint8Array>
}
